server:
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  application:
    name: product

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

