spring:
  application:
    name: eureka    #服务名称


server:
  port: 8761    #服务端口


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   #是否将自己注册到Eureka Server，默认为true。
#    register-with-eureka: false
    fetchRegistry: false    #是否从Eureka Server获取注册信息，默认为true。
#    fetch-registry: false
    serviceUrl:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka
