spring:
  application:
    name: feign

eureka:
  client:
    serviceUrl:
      defualtZone: http://192.168.0.125:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 5555

feign:
  hystrix:
    enabled: true
